nelmio_api_doc:
  documentation:
    #        schemes: [http, https]
    info:
      title: iService Backend Assessment
      description: Remote Jr PHP Developer - Javier Gonzalez
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api/vehicles # Accepts routes under /api/vehicles